#!/usr/bin/env bash

set -e
set -o pipefail

cd "$(dirname "$0")/.."

help() {
  echo "Usage: $0 TITLE [YYYY-MM-DD]"
}

if [ -z "$1" ]; then
  help >&2
  exit 1
fi

if [ "$1" = "-h" ]; then help; exit 0; fi

title="$1"
date="${2:-$(date +%Y-%m-%d)}"

filename="src/content/posts/$date--$(echo "$title" | sed 's/[^[:alnum:]]/-/g' | tr -s '-' | tr A-Z a-z)"

printf -- "---\ntitle: %s\ndate: %s\n---\n\n" "$title" "$date" > "$filename.md"

echo "Created new post at $filename.md"
